${
	["MoonSharp.Interpreter.Interop.AnonWrapper"] = ${
		skip = true,
	},
	["MoonSharp.Interpreter.Serialization.Json.JsonNull"] = ${
		skip = true,
	},
	["AimXRToolkit.Interactions.Proxies.ProxyButton"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyButton",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "AimXRToolkit.Interactions.Proxies.ProxyButton",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyButton",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "button",
								type = "AimXRToolkit.Interactions.Button",
								origtype = "AimXRToolkit.Interactions.Button",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyButton",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyButton",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyButton",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyButton",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
		},
		metamembers = ${ },
	},
	["AimXRToolkit.Interactions.Proxies.ProxyColor"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "AimXRToolkit.Interactions.Proxies.ProxyColor",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "color",
								type = "AimXRToolkit.Interactions.Color",
								origtype = "AimXRToolkit.Interactions.Color",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetColor = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetColor",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetColor",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "hexa",
								type = "System.String",
								origtype = "System.String",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetColor = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetColor",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetColor",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyColor",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
		},
		metamembers = ${ },
	},
	["AimXRToolkit.Interactions.Proxies.ProxySound"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "AimXRToolkit.Interactions.Proxies.ProxySound",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "sound",
								type = "AimXRToolkit.Interactions.Sound",
								origtype = "AimXRToolkit.Interactions.Sound",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			Play = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Play",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Play",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Stop = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Stop",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Stop",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			SetLoop = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetLoop",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetLoop",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "loop",
								type = "System.Boolean",
								origtype = "System.Boolean",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetLoop = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetLoop",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetLoop",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			SetVolume = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetVolume",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetVolume",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "volume",
								type = "System.Single",
								origtype = "System.Single",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetPlayOnStart = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetPlayOnStart",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetPlayOnStart",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "playOnStart",
								type = "System.Boolean",
								origtype = "System.Boolean",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			setSoundId = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "setSoundId",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "setSoundId",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "soundId",
								type = "System.Int32",
								origtype = "System.Int32",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySound",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
		},
		metamembers = ${ },
	},
	["AimXRToolkit.Interactions.Proxies.ProxySwitch"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "s",
								type = "AimXRToolkit.Interactions.Switch",
								origtype = "AimXRToolkit.Interactions.Switch",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetState = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetState",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetState",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "state",
								type = "System.Boolean",
								origtype = "System.Boolean",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetState = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetState",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetState",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			SetStop = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetStop",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetStop",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "angle",
								type = "System.Single",
								origtype = "System.Single",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySwitch",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
		},
		metamembers = ${ },
	},
	["AimXRToolkit.Interactions.Proxies.ProxyGrabbable"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			UseGravity = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "UseGravity",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyGrabbable",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "UseGravity",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyGrabbable",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "use",
								type = "System.Boolean",
								origtype = "System.Boolean",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyGrabbable",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyGrabbable",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyGrabbable",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyGrabbable",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
		},
		metamembers = ${ },
	},
	["AimXRToolkit.Interactions.Proxies.ProxySlider"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "AimXRToolkit.Interactions.Proxies.ProxySlider",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "slider",
								type = "AimXRToolkit.Interactions.Slider",
								origtype = "AimXRToolkit.Interactions.Slider",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetSpeed = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetSpeed",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetSpeed",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "speed",
								type = "System.Single",
								origtype = "System.Single",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GoTo = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GoTo",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GoTo",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "distance",
								type = "System.Single",
								origtype = "System.Single",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetStop = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetStop",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetStop",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "maxDisplacement",
								type = "System.Single",
								origtype = "System.Single",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetStop = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetStop",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetStop",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Single",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			StartMovement = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "StartMovement",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "StartMovement",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "reverse",
								type = "System.Boolean",
								origtype = "System.Boolean",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			StopMovement = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "StopMovement",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "StopMovement",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxySlider",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
		},
		metamembers = ${ },
	},
	["AimXRToolkit.Interactions.Proxies.ProxyHinge"] = ${
		visibility = "public",
		class = "MoonSharp.Interpreter.Interop.StandardUserDataDescriptor",
		members = ${
			__new = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "__new",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = ".ctor",
						ctor = true,
						special = true,
						visibility = "public",
						ret = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
						static = true,
						extension = false,
						params = ${
							[1] = ${
								name = "h",
								type = "AimXRToolkit.Interactions.Hinge",
								origtype = "AimXRToolkit.Interactions.Hinge",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetMinAngle = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetMinAngle",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetMinAngle",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "angle",
								type = "System.Single",
								origtype = "System.Single",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetMaxAngle = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetMaxAngle",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetMaxAngle",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "angle",
								type = "System.Single",
								origtype = "System.Single",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			UseLimits = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "UseLimits",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "UseLimits",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "use",
								type = "System.Boolean",
								origtype = "System.Boolean",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			UseGravity = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "UseGravity",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "UseGravity",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "use",
								type = "System.Boolean",
								origtype = "System.Boolean",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			SetTarget = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "SetTarget",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "SetTarget",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Void",
						decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "target",
								type = "System.String",
								origtype = "System.String",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetType = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetType",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetType",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Type",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			ToString = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "ToString",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "ToString",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.String",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
			Equals = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "Equals",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "Equals",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Boolean",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${
							[1] = ${
								name = "obj",
								type = "System.Object",
								origtype = "System.Object",
								default = false,
								out = false,
								ref = false,
								varargs = false,
								restricted = false,
							},
						},
					},
				},
			},
			GetHashCode = ${
				class = "MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor",
				name = "GetHashCode",
				decltype = "AimXRToolkit.Interactions.Proxies.ProxyHinge",
				overloads = ${
					[1] = ${
						class = "MoonSharp.Interpreter.Interop.MethodMemberDescriptor",
						name = "GetHashCode",
						ctor = false,
						special = false,
						visibility = "public",
						ret = "System.Int32",
						decltype = "System.Object",
						static = false,
						extension = false,
						params = ${ },
					},
				},
			},
		},
		metamembers = ${ },
	},
}
