//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.9168
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.6131.34058
// Compatible with MoonSharp v.2.0.0.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2023-05-30T16:45:56.0373076+02:00
// ----------------------------------------------------------
// 
// 
// 
namespace AimXRToolkit {
    
    
    public abstract class Hardwire {
        
        private Hardwire() {
        }
        
        public static void Initialize() {
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_34f05e5ec5984295abcc5c3c7240cea8());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_30e5e946639944cfbd818320d4170554());
        }
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        private sealed class TYPE_34f05e5ec5984295abcc5c3c7240cea8 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_34f05e5ec5984295abcc5c3c7240cea8() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyButton)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_52902eee6dd64d1984902c666ff45c35()}));
                this.AddMember("OnTouch", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("OnTouch", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a0aa9d474a7548b981f4905f430073ae()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_5a7474af18be4fb3996aa76240f50b6e()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_755f0df2ec2d4f09b129e8be399265d2()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_0cdc8e08067c41578b00c90230b940dd()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_167ac1e420d44d98bcce90b2759ac431()}));
            }
            
            private sealed class MTHD_52902eee6dd64d1984902c666ff45c35 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_52902eee6dd64d1984902c666ff45c35() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("button", typeof(AimXRToolkit.Interactions.Button), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyButton(((AimXRToolkit.Interactions.Button)(pars[0])));
                }
            }
            
            private sealed class MTHD_a0aa9d474a7548b981f4905f430073ae : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a0aa9d474a7548b981f4905f430073ae() {
                    this.Initialize("OnTouch", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyButton)(obj)).OnTouch();
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_5a7474af18be4fb3996aa76240f50b6e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_5a7474af18be4fb3996aa76240f50b6e() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_755f0df2ec2d4f09b129e8be399265d2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_755f0df2ec2d4f09b129e8be399265d2() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_0cdc8e08067c41578b00c90230b940dd : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_0cdc8e08067c41578b00c90230b940dd() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_167ac1e420d44d98bcce90b2759ac431 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_167ac1e420d44d98bcce90b2759ac431() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        private sealed class TYPE_30e5e946639944cfbd818320d4170554 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_30e5e946639944cfbd818320d4170554() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyColor)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_0f6e63ad89e345fea2d00af27ef1c30d()}));
                this.AddMember("SetColor", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetColor", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_acb859de140b44dbab2af9c3c4bb0756()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_0a4283f35d904ba9ae558fda4e863ff9()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_7daf9ff85b764c91b7c824131b1df6b5()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_253720961e9c42b599032403be3f7c8a()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a935e7b2eb2a43c29d1c0fd7c0d0d2c1()}));
            }
            
            private sealed class MTHD_0f6e63ad89e345fea2d00af27ef1c30d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_0f6e63ad89e345fea2d00af27ef1c30d() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("color", typeof(AimXRToolkit.Interactions.Color), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyColor(((AimXRToolkit.Interactions.Color)(pars[0])));
                }
            }
            
            private sealed class MTHD_acb859de140b44dbab2af9c3c4bb0756 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_acb859de140b44dbab2af9c3c4bb0756() {
                    this.Initialize("SetColor", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("hexa", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyColor)(obj)).SetColor(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_0a4283f35d904ba9ae558fda4e863ff9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_0a4283f35d904ba9ae558fda4e863ff9() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_7daf9ff85b764c91b7c824131b1df6b5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_7daf9ff85b764c91b7c824131b1df6b5() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_253720961e9c42b599032403be3f7c8a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_253720961e9c42b599032403be3f7c8a() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_a935e7b2eb2a43c29d1c0fd7c0d0d2c1 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a935e7b2eb2a43c29d1c0fd7c0d0d2c1() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
    }
}
