//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.9168
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.6131.34058
// Compatible with MoonSharp v.2.0.0.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2023-06-08T15:18:11.3753013+02:00
// ----------------------------------------------------------
// 
// 
// 
namespace AimXRToolkit {
    
    
    public abstract class Hardwire {
        
        private Hardwire() {
        }
        
        public static void Initialize() {
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_db4dd1025d8644f898c33c37c6cd592d());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_c28d8a5f30084cbd91c94b3fb230553e());
        }
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        private sealed class TYPE_db4dd1025d8644f898c33c37c6cd592d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_db4dd1025d8644f898c33c37c6cd592d() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyButton)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_635949f9729f49b7b04cb848a9c184d7()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_167eca7478af42c9b52cd2ca62dd1a65()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d6c861baf9c84ba985dba8b9e679f9ed()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b15b37e9e38b40638ecd97ab9ce903b1()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_16ce0b0ef1f049f1ac9a8f7c66cdaeba()}));
            }
            
            private sealed class MTHD_635949f9729f49b7b04cb848a9c184d7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_635949f9729f49b7b04cb848a9c184d7() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("button", typeof(AimXRToolkit.Interactions.Button), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyButton(((AimXRToolkit.Interactions.Button)(pars[0])));
                }
            }
            
            private sealed class MTHD_167eca7478af42c9b52cd2ca62dd1a65 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_167eca7478af42c9b52cd2ca62dd1a65() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_d6c861baf9c84ba985dba8b9e679f9ed : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d6c861baf9c84ba985dba8b9e679f9ed() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_b15b37e9e38b40638ecd97ab9ce903b1 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b15b37e9e38b40638ecd97ab9ce903b1() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_16ce0b0ef1f049f1ac9a8f7c66cdaeba : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_16ce0b0ef1f049f1ac9a8f7c66cdaeba() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        private sealed class TYPE_c28d8a5f30084cbd91c94b3fb230553e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_c28d8a5f30084cbd91c94b3fb230553e() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyColor)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3821c82fa9c34016be1d17a899f1aedf()}));
                this.AddMember("SetColor", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetColor", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_30037adb89e84049ad6c65e7b485b509()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9b3ae3db87e8404ab57fcb4ce019a812()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1a9d44b51fc04615b7dc7262d1e66f4c()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_76bf513c83334a158a54c198c88abe1e()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_41502e52cbfc48cb830eab1135047112()}));
            }
            
            private sealed class MTHD_3821c82fa9c34016be1d17a899f1aedf : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3821c82fa9c34016be1d17a899f1aedf() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("color", typeof(AimXRToolkit.Interactions.Color), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyColor(((AimXRToolkit.Interactions.Color)(pars[0])));
                }
            }
            
            private sealed class MTHD_30037adb89e84049ad6c65e7b485b509 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_30037adb89e84049ad6c65e7b485b509() {
                    this.Initialize("SetColor", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("hexa", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyColor)(obj)).SetColor(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_9b3ae3db87e8404ab57fcb4ce019a812 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_9b3ae3db87e8404ab57fcb4ce019a812() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_1a9d44b51fc04615b7dc7262d1e66f4c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1a9d44b51fc04615b7dc7262d1e66f4c() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_76bf513c83334a158a54c198c88abe1e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_76bf513c83334a158a54c198c88abe1e() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_41502e52cbfc48cb830eab1135047112 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_41502e52cbfc48cb830eab1135047112() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
    }
}
