//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.9171
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.6131.34058
// Compatible with MoonSharp v.2.0.0.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2023-07-03T13:38:50.7716439+02:00
// ----------------------------------------------------------
// 
// 
// 
namespace AimXRToolkit {
    
    
    public abstract class Hardwire {
        
        private Hardwire() {
        }
        
        public static void Initialize() {
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_a53d9ec68d2e4389925ff28124244f34());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_3016a03e54bb400abd5619debeda9a21());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_20a1ca50d007401a914074828442d6f5());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_da1b24e9f93c471cb34ba35ce0c488eb());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_f8c74245ceef4ee1ae85999d89936283());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_7228e97c4ee44296ac73b5ab66b781fc());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_0c9562b1938e4dbfa120d8f4e0c30c5d());
        }
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        private sealed class TYPE_a53d9ec68d2e4389925ff28124244f34 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_a53d9ec68d2e4389925ff28124244f34() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyButton)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_5512930088c6420c83192c59a96b65e7()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_121b143cdb29413aad0c2c06f0313cab()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_673db541c12f4756a3e4acbbc5312790()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_5ebe5570fd6f479b9bf97c748dfea135()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_38bdebef46b94c24938a0feaa6e647d9()}));
            }
            
            private sealed class MTHD_5512930088c6420c83192c59a96b65e7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_5512930088c6420c83192c59a96b65e7() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("button", typeof(AimXRToolkit.Interactions.Button), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyButton(((AimXRToolkit.Interactions.Button)(pars[0])));
                }
            }
            
            private sealed class MTHD_121b143cdb29413aad0c2c06f0313cab : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_121b143cdb29413aad0c2c06f0313cab() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_673db541c12f4756a3e4acbbc5312790 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_673db541c12f4756a3e4acbbc5312790() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_5ebe5570fd6f479b9bf97c748dfea135 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_5ebe5570fd6f479b9bf97c748dfea135() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_38bdebef46b94c24938a0feaa6e647d9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_38bdebef46b94c24938a0feaa6e647d9() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        private sealed class TYPE_3016a03e54bb400abd5619debeda9a21 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_3016a03e54bb400abd5619debeda9a21() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyColor)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f2d0d7aaa4e0418e888007debf3df1b7()}));
                this.AddMember("SetColor", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetColor", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f55d85909e3b4a9fb58114a219126942()}));
                this.AddMember("GetColor", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetColor", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_311fa1a9ec404e588656f203969642de()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1d510a16850d4955b3b15ba80f8fa1bf()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1995ed56f38e4188b2be43f68fb4d14b()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8f7e3f5cf63149d9beeda63e97f7400f()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_25094dc463d94a5eaff1e206ca32990a()}));
            }
            
            private sealed class MTHD_f2d0d7aaa4e0418e888007debf3df1b7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f2d0d7aaa4e0418e888007debf3df1b7() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("color", typeof(AimXRToolkit.Interactions.Color), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyColor(((AimXRToolkit.Interactions.Color)(pars[0])));
                }
            }
            
            private sealed class MTHD_f55d85909e3b4a9fb58114a219126942 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f55d85909e3b4a9fb58114a219126942() {
                    this.Initialize("SetColor", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("hexa", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyColor)(obj)).SetColor(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_311fa1a9ec404e588656f203969642de : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_311fa1a9ec404e588656f203969642de() {
                    this.Initialize("GetColor", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((AimXRToolkit.Interactions.Proxies.ProxyColor)(obj)).GetColor();
                }
            }
            
            private sealed class MTHD_1d510a16850d4955b3b15ba80f8fa1bf : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1d510a16850d4955b3b15ba80f8fa1bf() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_1995ed56f38e4188b2be43f68fb4d14b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1995ed56f38e4188b2be43f68fb4d14b() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_8f7e3f5cf63149d9beeda63e97f7400f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8f7e3f5cf63149d9beeda63e97f7400f() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_25094dc463d94a5eaff1e206ca32990a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_25094dc463d94a5eaff1e206ca32990a() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxySound
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxySound
        private sealed class TYPE_20a1ca50d007401a914074828442d6f5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_20a1ca50d007401a914074828442d6f5() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxySound)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2876d4c43c6d48a8b6c7eea218e7c908()}));
                this.AddMember("Play", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Play", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_fbd24a79e88742278a3c7201e31b8bca()}));
                this.AddMember("Stop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Stop", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_4fb5f5f54c674d0496759f285ee448a9()}));
                this.AddMember("SetLoop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetLoop", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c62abba06db94aedae1609d092e06eee()}));
                this.AddMember("GetLoop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetLoop", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_53111c967aee4454a1e6365701fb8eb2()}));
                this.AddMember("SetVolume", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetVolume", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cb734ef51f5b4846b539872a4c04f48d()}));
                this.AddMember("SetPlayOnStart", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayOnStart", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9d071701aa13471993da7729d6899d16()}));
                this.AddMember("setSoundId", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("setSoundId", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ee3b3261168f4eea833e70d3715a774e()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_64d55d45c913416fa2ef37477f76bb62()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_88183844910d4934ba07505b1d78fb9a()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_6cafed7ea64d4bcbaaeae088f90ff76a()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ffd6a4511b8a48b8b6d9d051922ab528()}));
            }
            
            private sealed class MTHD_2876d4c43c6d48a8b6c7eea218e7c908 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2876d4c43c6d48a8b6c7eea218e7c908() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("sound", typeof(AimXRToolkit.Interactions.Sound), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxySound(((AimXRToolkit.Interactions.Sound)(pars[0])));
                }
            }
            
            private sealed class MTHD_fbd24a79e88742278a3c7201e31b8bca : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_fbd24a79e88742278a3c7201e31b8bca() {
                    this.Initialize("Play", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).Play();
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_4fb5f5f54c674d0496759f285ee448a9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_4fb5f5f54c674d0496759f285ee448a9() {
                    this.Initialize("Stop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).Stop();
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_c62abba06db94aedae1609d092e06eee : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c62abba06db94aedae1609d092e06eee() {
                    this.Initialize("SetLoop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("loop", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).SetLoop(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_53111c967aee4454a1e6365701fb8eb2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_53111c967aee4454a1e6365701fb8eb2() {
                    this.Initialize("GetLoop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).GetLoop();
                }
            }
            
            private sealed class MTHD_cb734ef51f5b4846b539872a4c04f48d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cb734ef51f5b4846b539872a4c04f48d() {
                    this.Initialize("SetVolume", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("volume", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).SetVolume(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_9d071701aa13471993da7729d6899d16 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_9d071701aa13471993da7729d6899d16() {
                    this.Initialize("SetPlayOnStart", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("playOnStart", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).SetPlayOnStart(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_ee3b3261168f4eea833e70d3715a774e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_ee3b3261168f4eea833e70d3715a774e() {
                    this.Initialize("setSoundId", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("soundId", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).setSoundId(((int)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_64d55d45c913416fa2ef37477f76bb62 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_64d55d45c913416fa2ef37477f76bb62() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_88183844910d4934ba07505b1d78fb9a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_88183844910d4934ba07505b1d78fb9a() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_6cafed7ea64d4bcbaaeae088f90ff76a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_6cafed7ea64d4bcbaaeae088f90ff76a() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_ffd6a4511b8a48b8b6d9d051922ab528 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_ffd6a4511b8a48b8b6d9d051922ab528() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxySwitch
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxySwitch
        private sealed class TYPE_da1b24e9f93c471cb34ba35ce0c488eb : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_da1b24e9f93c471cb34ba35ce0c488eb() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_aabbe0eb5c1d4fdc91fd3793bed97941()}));
                this.AddMember("SetState", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetState", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f69308a406514b33816e5a6547997442()}));
                this.AddMember("GetState", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetState", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_30e250997ffb4030b9d997153b4eca33()}));
                this.AddMember("SetStop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetStop", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f869bc9c5d654ecb8759562166e37d81()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d8d2e946cfdb476695cfda22498f8b63()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_07fd1fa93c08466eaaf1d0e12562db17()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8cbb401d15e140a08d9534a8f99307f2()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ec2efa69d51845fcb52215216c1fc0cd()}));
            }
            
            private sealed class MTHD_aabbe0eb5c1d4fdc91fd3793bed97941 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_aabbe0eb5c1d4fdc91fd3793bed97941() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("s", typeof(AimXRToolkit.Interactions.Switch), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxySwitch(((AimXRToolkit.Interactions.Switch)(pars[0])));
                }
            }
            
            private sealed class MTHD_f69308a406514b33816e5a6547997442 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f69308a406514b33816e5a6547997442() {
                    this.Initialize("SetState", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("state", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySwitch)(obj)).SetState(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_30e250997ffb4030b9d997153b4eca33 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_30e250997ffb4030b9d997153b4eca33() {
                    this.Initialize("GetState", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((AimXRToolkit.Interactions.Proxies.ProxySwitch)(obj)).GetState();
                }
            }
            
            private sealed class MTHD_f869bc9c5d654ecb8759562166e37d81 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f869bc9c5d654ecb8759562166e37d81() {
                    this.Initialize("SetStop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("angle", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySwitch)(obj)).SetStop(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_d8d2e946cfdb476695cfda22498f8b63 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d8d2e946cfdb476695cfda22498f8b63() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_07fd1fa93c08466eaaf1d0e12562db17 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_07fd1fa93c08466eaaf1d0e12562db17() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_8cbb401d15e140a08d9534a8f99307f2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8cbb401d15e140a08d9534a8f99307f2() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_ec2efa69d51845fcb52215216c1fc0cd : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_ec2efa69d51845fcb52215216c1fc0cd() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyGrabbable
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyGrabbable
        private sealed class TYPE_f8c74245ceef4ee1ae85999d89936283 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_f8c74245ceef4ee1ae85999d89936283() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable)) {
                this.AddMember("UseGravity", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("UseGravity", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2b63f08262b5482db034225509377d23()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e467ce2e522d4a7d861f6fb7a194e442()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_707e01a40bd34f0e8ebba7d86af73f63()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_db9f1cb3c66a4df7ada9bc977110e994()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_0d61addcbad94e2487f05fad8b2d136a()}));
            }
            
            private sealed class MTHD_2b63f08262b5482db034225509377d23 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2b63f08262b5482db034225509377d23() {
                    this.Initialize("UseGravity", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("use", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyGrabbable)(obj)).UseGravity(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_e467ce2e522d4a7d861f6fb7a194e442 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e467ce2e522d4a7d861f6fb7a194e442() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_707e01a40bd34f0e8ebba7d86af73f63 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_707e01a40bd34f0e8ebba7d86af73f63() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_db9f1cb3c66a4df7ada9bc977110e994 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_db9f1cb3c66a4df7ada9bc977110e994() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_0d61addcbad94e2487f05fad8b2d136a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_0d61addcbad94e2487f05fad8b2d136a() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxySlider
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxySlider
        private sealed class TYPE_7228e97c4ee44296ac73b5ab66b781fc : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_7228e97c4ee44296ac73b5ab66b781fc() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxySlider)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_edfe74352d3649d2bf9a989827e62ee4()}));
                this.AddMember("SetSpeed", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetSpeed", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_75e8b7d07fec4f79b95ebfef1f1834ea()}));
                this.AddMember("GoTo", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GoTo", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_91b012b70e9f4a50b4764559d437b905()}));
                this.AddMember("SetStop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetStop", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e2d56e932c154ad38d33ffc85e6f8cc4()}));
                this.AddMember("GetStop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetStop", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2d82f518d3db4b18a1483c3fa6ad18d5()}));
                this.AddMember("StartMovement", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("StartMovement", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3576952e5d394882afcc125bf101afab()}));
                this.AddMember("StopMovement", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("StopMovement", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2734878c0d664af7a528832590d27864()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d3f5ac7bbb974eee8759d719edac7a15()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_58b03fec8e55443385b208cec5192115()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_df97aa6dc88843ada19373c856c4b49a()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a203eb46957c44c99e5b2651df3cde7a()}));
            }
            
            private sealed class MTHD_edfe74352d3649d2bf9a989827e62ee4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_edfe74352d3649d2bf9a989827e62ee4() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("slider", typeof(AimXRToolkit.Interactions.Slider), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxySlider(((AimXRToolkit.Interactions.Slider)(pars[0])));
                }
            }
            
            private sealed class MTHD_75e8b7d07fec4f79b95ebfef1f1834ea : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_75e8b7d07fec4f79b95ebfef1f1834ea() {
                    this.Initialize("SetSpeed", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("speed", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).SetSpeed(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_91b012b70e9f4a50b4764559d437b905 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_91b012b70e9f4a50b4764559d437b905() {
                    this.Initialize("GoTo", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("distance", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).GoTo(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_e2d56e932c154ad38d33ffc85e6f8cc4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e2d56e932c154ad38d33ffc85e6f8cc4() {
                    this.Initialize("SetStop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("maxDisplacement", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).SetStop(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_2d82f518d3db4b18a1483c3fa6ad18d5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2d82f518d3db4b18a1483c3fa6ad18d5() {
                    this.Initialize("GetStop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).GetStop();
                }
            }
            
            private sealed class MTHD_3576952e5d394882afcc125bf101afab : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3576952e5d394882afcc125bf101afab() {
                    this.Initialize("StartMovement", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("reverse", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).StartMovement(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_2734878c0d664af7a528832590d27864 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2734878c0d664af7a528832590d27864() {
                    this.Initialize("StopMovement", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).StopMovement();
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_d3f5ac7bbb974eee8759d719edac7a15 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d3f5ac7bbb974eee8759d719edac7a15() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_58b03fec8e55443385b208cec5192115 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_58b03fec8e55443385b208cec5192115() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_df97aa6dc88843ada19373c856c4b49a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_df97aa6dc88843ada19373c856c4b49a() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_a203eb46957c44c99e5b2651df3cde7a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a203eb46957c44c99e5b2651df3cde7a() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyHinge
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyHinge
        private sealed class TYPE_0c9562b1938e4dbfa120d8f4e0c30c5d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_0c9562b1938e4dbfa120d8f4e0c30c5d() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a4e277a619014d888e136855d6b4a37e()}));
                this.AddMember("SetMinAngle", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetMinAngle", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b4cec4e2029740fe87cb87d029e19047()}));
                this.AddMember("SetMaxAngle", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetMaxAngle", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_5d9e77ce32b54775a3d87ddb628667a3()}));
                this.AddMember("UseLimits", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("UseLimits", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_76d603db5543444b8ffb5617dabf9ba0()}));
                this.AddMember("UseGravity", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("UseGravity", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1dc0bac791df410bbb964097f2ad0b5e()}));
                this.AddMember("SetTarget", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetTarget", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d812a63c643c4e39b1f02f9aa9f3dfe4()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2a9a1733cf1e4af39eecc2fe4fd4fe04()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a29639f38c764b73891bb16efefce328()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_72f11142809741ea933eb8272ec6f3d0()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a0c50ef5b5644d5fad0cd38e2023aeb2()}));
            }
            
            private sealed class MTHD_a4e277a619014d888e136855d6b4a37e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a4e277a619014d888e136855d6b4a37e() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("h", typeof(AimXRToolkit.Interactions.Hinge), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyHinge(((AimXRToolkit.Interactions.Hinge)(pars[0])));
                }
            }
            
            private sealed class MTHD_b4cec4e2029740fe87cb87d029e19047 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b4cec4e2029740fe87cb87d029e19047() {
                    this.Initialize("SetMinAngle", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("angle", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).SetMinAngle(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_5d9e77ce32b54775a3d87ddb628667a3 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_5d9e77ce32b54775a3d87ddb628667a3() {
                    this.Initialize("SetMaxAngle", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("angle", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).SetMaxAngle(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_76d603db5543444b8ffb5617dabf9ba0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_76d603db5543444b8ffb5617dabf9ba0() {
                    this.Initialize("UseLimits", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("use", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).UseLimits(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_1dc0bac791df410bbb964097f2ad0b5e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1dc0bac791df410bbb964097f2ad0b5e() {
                    this.Initialize("UseGravity", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("use", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).UseGravity(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_d812a63c643c4e39b1f02f9aa9f3dfe4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d812a63c643c4e39b1f02f9aa9f3dfe4() {
                    this.Initialize("SetTarget", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("target", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).SetTarget(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_2a9a1733cf1e4af39eecc2fe4fd4fe04 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2a9a1733cf1e4af39eecc2fe4fd4fe04() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_a29639f38c764b73891bb16efefce328 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a29639f38c764b73891bb16efefce328() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_72f11142809741ea933eb8272ec6f3d0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_72f11142809741ea933eb8272ec6f3d0() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_a0c50ef5b5644d5fad0cd38e2023aeb2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a0c50ef5b5644d5fad0cd38e2023aeb2() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
    }
}
