//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.9171
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.6131.34058
// Compatible with MoonSharp v.2.0.0.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2023-06-22T14:38:43.6181280+02:00
// ----------------------------------------------------------
// 
// 
// 
namespace AimXRToolkit {
    
    
    public abstract class Hardwire {
        
        private Hardwire() {
        }
        
        public static void Initialize() {
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_248fc87941824449a4e0e966b8218700());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_717e5cce6e89433981b10f11940b4744());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_dfeb504ef399468ebeadf7de7382f11d());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_47d7739469374803899d6f23644361c9());
        }
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        private sealed class TYPE_248fc87941824449a4e0e966b8218700 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_248fc87941824449a4e0e966b8218700() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyButton)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b6282aa827a24b1192ccc1df9e940e15()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_44a28d575bf14fcfb1716ba04f30a102()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_76a3aa3efa774d4fa0646b857a92dab6()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_177993555e2e42b58ee8ca298b2723e2()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e4146180017f4f9c81e862e0549b5dc4()}));
            }
            
            private sealed class MTHD_b6282aa827a24b1192ccc1df9e940e15 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b6282aa827a24b1192ccc1df9e940e15() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("button", typeof(AimXRToolkit.Interactions.Button), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyButton(((AimXRToolkit.Interactions.Button)(pars[0])));
                }
            }
            
            private sealed class MTHD_44a28d575bf14fcfb1716ba04f30a102 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_44a28d575bf14fcfb1716ba04f30a102() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_76a3aa3efa774d4fa0646b857a92dab6 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_76a3aa3efa774d4fa0646b857a92dab6() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_177993555e2e42b58ee8ca298b2723e2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_177993555e2e42b58ee8ca298b2723e2() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_e4146180017f4f9c81e862e0549b5dc4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e4146180017f4f9c81e862e0549b5dc4() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        private sealed class TYPE_717e5cce6e89433981b10f11940b4744 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_717e5cce6e89433981b10f11940b4744() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyColor)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8ec1e364bcf84c79b5f8a05a591fe259()}));
                this.AddMember("SetColor", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetColor", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a8edd12319db4742950c8cddebff071d()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_75c5eb7eae1a4b98a1d69376e7442d5e()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f56e61d181eb4efeb75cca3690154b0f()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_58e598286b504651b38ea79a1ec19837()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_eb144c50c0a84a338c95f1b9e5f0f9ff()}));
            }
            
            private sealed class MTHD_8ec1e364bcf84c79b5f8a05a591fe259 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8ec1e364bcf84c79b5f8a05a591fe259() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("color", typeof(AimXRToolkit.Interactions.Color), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyColor(((AimXRToolkit.Interactions.Color)(pars[0])));
                }
            }
            
            private sealed class MTHD_a8edd12319db4742950c8cddebff071d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a8edd12319db4742950c8cddebff071d() {
                    this.Initialize("SetColor", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("hexa", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyColor)(obj)).SetColor(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_75c5eb7eae1a4b98a1d69376e7442d5e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_75c5eb7eae1a4b98a1d69376e7442d5e() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_f56e61d181eb4efeb75cca3690154b0f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f56e61d181eb4efeb75cca3690154b0f() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_58e598286b504651b38ea79a1ec19837 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_58e598286b504651b38ea79a1ec19837() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_eb144c50c0a84a338c95f1b9e5f0f9ff : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_eb144c50c0a84a338c95f1b9e5f0f9ff() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxySound
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxySound
        private sealed class TYPE_dfeb504ef399468ebeadf7de7382f11d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_dfeb504ef399468ebeadf7de7382f11d() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxySound)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b6dcd397faae400cb242232163b3a369()}));
                this.AddMember("Play", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Play", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b4897733afcf4fad9a9ecb5545c62b02()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c64fdca5421d4a3fba5c49a7727115d6()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ebc8d88d3ef24e6780c770e8a1c8b575()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cd09f40043464fc8987e89bdf3474ef8()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_471aef7b789d46918e041cee2b9a99a0()}));
            }
            
            private sealed class MTHD_b6dcd397faae400cb242232163b3a369 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b6dcd397faae400cb242232163b3a369() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("sound", typeof(AimXRToolkit.Interactions.Sound), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxySound(((AimXRToolkit.Interactions.Sound)(pars[0])));
                }
            }
            
            private sealed class MTHD_b4897733afcf4fad9a9ecb5545c62b02 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b4897733afcf4fad9a9ecb5545c62b02() {
                    this.Initialize("Play", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).Play();
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_c64fdca5421d4a3fba5c49a7727115d6 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c64fdca5421d4a3fba5c49a7727115d6() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_ebc8d88d3ef24e6780c770e8a1c8b575 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_ebc8d88d3ef24e6780c770e8a1c8b575() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_cd09f40043464fc8987e89bdf3474ef8 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cd09f40043464fc8987e89bdf3474ef8() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_471aef7b789d46918e041cee2b9a99a0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_471aef7b789d46918e041cee2b9a99a0() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxySwitch
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxySwitch
        private sealed class TYPE_47d7739469374803899d6f23644361c9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_47d7739469374803899d6f23644361c9() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_580c7a408610411381c19baf65cb4546()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b0a2e12a5e0d4ae7bc43356932872ff4()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1457098837f042c186b22e070c761d74()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2275ad23a96d424cb6d89fc5a4be29d9()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e06591b4e2ca4c9882a34d4c71278eab()}));
            }
            
            private sealed class MTHD_580c7a408610411381c19baf65cb4546 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_580c7a408610411381c19baf65cb4546() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("s", typeof(AimXRToolkit.Interactions.Switch), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxySwitch(((AimXRToolkit.Interactions.Switch)(pars[0])));
                }
            }
            
            private sealed class MTHD_b0a2e12a5e0d4ae7bc43356932872ff4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b0a2e12a5e0d4ae7bc43356932872ff4() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_1457098837f042c186b22e070c761d74 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1457098837f042c186b22e070c761d74() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_2275ad23a96d424cb6d89fc5a4be29d9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2275ad23a96d424cb6d89fc5a4be29d9() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_e06591b4e2ca4c9882a34d4c71278eab : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e06591b4e2ca4c9882a34d4c71278eab() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
    }
}
