//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.9172
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.6131.34058
// Compatible with MoonSharp v.2.0.0.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2023-07-18T17:13:01.6539254+02:00
// ----------------------------------------------------------
// 
// 
// 
namespace AimXRToolkit {
    
    
    public abstract class Hardwire {
        
        private Hardwire() {
        }
        
        public static void Initialize() {
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_2d70c890ec39408d98e24313220f14a4());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_7a040171d2a444a6990ffee67791f1c8());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_7c624a95911d410f96e2db517c997c9b());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_e8edef0f437044e6be64abdc220355bb());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_2e762b9aed5848c39384d8a1e92e9092());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_dad19dd4e7a34ea98971163634af7e0c());
            MoonSharp.Interpreter.UserData.RegisterType(new TYPE_09e41b71e36345b0834f968be26be7d7());
        }
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyButton
        private sealed class TYPE_2d70c890ec39408d98e24313220f14a4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_2d70c890ec39408d98e24313220f14a4() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyButton)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_94ccfaeeb2d04e05a9da05f4983b1d15()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_485a33e865d24a718b07dcba7a9ea161()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e4f8ed5a1105415797f53f225e36831a()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_29e8927567c2434398e2084e2b71e7bf()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyButton), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_753d42793792459aa89daddd58aca94f()}));
            }
            
            private sealed class MTHD_94ccfaeeb2d04e05a9da05f4983b1d15 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_94ccfaeeb2d04e05a9da05f4983b1d15() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("button", typeof(AimXRToolkit.Interactions.Button), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyButton(((AimXRToolkit.Interactions.Button)(pars[0])));
                }
            }
            
            private sealed class MTHD_485a33e865d24a718b07dcba7a9ea161 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_485a33e865d24a718b07dcba7a9ea161() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_e4f8ed5a1105415797f53f225e36831a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e4f8ed5a1105415797f53f225e36831a() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_29e8927567c2434398e2084e2b71e7bf : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_29e8927567c2434398e2084e2b71e7bf() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_753d42793792459aa89daddd58aca94f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_753d42793792459aa89daddd58aca94f() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyColor
        private sealed class TYPE_7a040171d2a444a6990ffee67791f1c8 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_7a040171d2a444a6990ffee67791f1c8() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyColor)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d5502951a06744b789cc8a94d1343752()}));
                this.AddMember("SetColor", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetColor", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_62a0baa05efa4078918b6a8a0fc7baf5()}));
                this.AddMember("GetColor", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetColor", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f1e491bdf9ea4e16a11de391f1b70dd9()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d249b7ea22e741c1bd18c87566db8e85()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b4003e9211f1461481b531327583f770()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_abc7afa8301f4af1ad2c7af66b8a4f0c()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyColor), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_139f7129c339480fa0511e0e026f2c73()}));
            }
            
            private sealed class MTHD_d5502951a06744b789cc8a94d1343752 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d5502951a06744b789cc8a94d1343752() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("color", typeof(AimXRToolkit.Interactions.Color), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyColor(((AimXRToolkit.Interactions.Color)(pars[0])));
                }
            }
            
            private sealed class MTHD_62a0baa05efa4078918b6a8a0fc7baf5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_62a0baa05efa4078918b6a8a0fc7baf5() {
                    this.Initialize("SetColor", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("hexa", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyColor)(obj)).SetColor(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_f1e491bdf9ea4e16a11de391f1b70dd9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_f1e491bdf9ea4e16a11de391f1b70dd9() {
                    this.Initialize("GetColor", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((AimXRToolkit.Interactions.Proxies.ProxyColor)(obj)).GetColor();
                }
            }
            
            private sealed class MTHD_d249b7ea22e741c1bd18c87566db8e85 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d249b7ea22e741c1bd18c87566db8e85() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_b4003e9211f1461481b531327583f770 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b4003e9211f1461481b531327583f770() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_abc7afa8301f4af1ad2c7af66b8a4f0c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_abc7afa8301f4af1ad2c7af66b8a4f0c() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_139f7129c339480fa0511e0e026f2c73 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_139f7129c339480fa0511e0e026f2c73() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxySound
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxySound
        private sealed class TYPE_7c624a95911d410f96e2db517c997c9b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_7c624a95911d410f96e2db517c997c9b() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxySound)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_94a70dd4c7fc41d5bbed9374365421d2()}));
                this.AddMember("Play", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Play", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_4b37d6feffb4476da9dbd813cf6d73de()}));
                this.AddMember("Stop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Stop", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_85a81129669a4e88844334db04060941()}));
                this.AddMember("SetLoop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetLoop", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3616617594514950a9bd43d079567b0d()}));
                this.AddMember("GetLoop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetLoop", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_798dc0bcd8064e0685819a246323402e()}));
                this.AddMember("SetVolume", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetVolume", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d9bb14a58ad445c0ba39a905e2c42559()}));
                this.AddMember("SetPlayOnStart", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetPlayOnStart", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_6f2b70b672db4d81baf20c482557f910()}));
                this.AddMember("setSoundId", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("setSoundId", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_54381bce694642429ea7eb6fa61a0b8a()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_4e2dd72cbb0941daa15de647628b2ae6()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_61a1d380b75645f685fed5eba6db2b09()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ee4c01c9e15346ebb24b7e09c54cc6aa()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxySound), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_1121013dc96a43979d2e8c8c701474be()}));
            }
            
            private sealed class MTHD_94a70dd4c7fc41d5bbed9374365421d2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_94a70dd4c7fc41d5bbed9374365421d2() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("sound", typeof(AimXRToolkit.Interactions.Sound), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxySound(((AimXRToolkit.Interactions.Sound)(pars[0])));
                }
            }
            
            private sealed class MTHD_4b37d6feffb4476da9dbd813cf6d73de : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_4b37d6feffb4476da9dbd813cf6d73de() {
                    this.Initialize("Play", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).Play();
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_85a81129669a4e88844334db04060941 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_85a81129669a4e88844334db04060941() {
                    this.Initialize("Stop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).Stop();
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_3616617594514950a9bd43d079567b0d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3616617594514950a9bd43d079567b0d() {
                    this.Initialize("SetLoop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("loop", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).SetLoop(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_798dc0bcd8064e0685819a246323402e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_798dc0bcd8064e0685819a246323402e() {
                    this.Initialize("GetLoop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).GetLoop();
                }
            }
            
            private sealed class MTHD_d9bb14a58ad445c0ba39a905e2c42559 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_d9bb14a58ad445c0ba39a905e2c42559() {
                    this.Initialize("SetVolume", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("volume", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).SetVolume(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_6f2b70b672db4d81baf20c482557f910 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_6f2b70b672db4d81baf20c482557f910() {
                    this.Initialize("SetPlayOnStart", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("playOnStart", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).SetPlayOnStart(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_54381bce694642429ea7eb6fa61a0b8a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_54381bce694642429ea7eb6fa61a0b8a() {
                    this.Initialize("setSoundId", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("soundId", typeof(int), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySound)(obj)).setSoundId(((int)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_4e2dd72cbb0941daa15de647628b2ae6 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_4e2dd72cbb0941daa15de647628b2ae6() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_61a1d380b75645f685fed5eba6db2b09 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_61a1d380b75645f685fed5eba6db2b09() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_ee4c01c9e15346ebb24b7e09c54cc6aa : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_ee4c01c9e15346ebb24b7e09c54cc6aa() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_1121013dc96a43979d2e8c8c701474be : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_1121013dc96a43979d2e8c8c701474be() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxySwitch
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxySwitch
        private sealed class TYPE_e8edef0f437044e6be64abdc220355bb : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_e8edef0f437044e6be64abdc220355bb() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c41ae8e3487e4bdfabf7ccc5ff6d8b86()}));
                this.AddMember("SetState", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetState", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c669b5db22c643288eeb98ef91d78110()}));
                this.AddMember("GetState", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetState", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3824dd79644b459894ce7edaf5448d8b()}));
                this.AddMember("SetStop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetStop", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e1fe41416a764360bb826b3e1fa97f20()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9460e531c21b496bbab515a37bd99964()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e41ad1bfbc224e28808f39e98dc978c5()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_7940653b8f524c34a987d6d8774af217()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxySwitch), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_84c943b62b964a5f84e586642e3af5fd()}));
            }
            
            private sealed class MTHD_c41ae8e3487e4bdfabf7ccc5ff6d8b86 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c41ae8e3487e4bdfabf7ccc5ff6d8b86() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("s", typeof(AimXRToolkit.Interactions.Switch), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxySwitch(((AimXRToolkit.Interactions.Switch)(pars[0])));
                }
            }
            
            private sealed class MTHD_c669b5db22c643288eeb98ef91d78110 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_c669b5db22c643288eeb98ef91d78110() {
                    this.Initialize("SetState", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("state", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySwitch)(obj)).SetState(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_3824dd79644b459894ce7edaf5448d8b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3824dd79644b459894ce7edaf5448d8b() {
                    this.Initialize("GetState", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((AimXRToolkit.Interactions.Proxies.ProxySwitch)(obj)).GetState();
                }
            }
            
            private sealed class MTHD_e1fe41416a764360bb826b3e1fa97f20 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e1fe41416a764360bb826b3e1fa97f20() {
                    this.Initialize("SetStop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("angle", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySwitch)(obj)).SetStop(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_9460e531c21b496bbab515a37bd99964 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_9460e531c21b496bbab515a37bd99964() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_e41ad1bfbc224e28808f39e98dc978c5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e41ad1bfbc224e28808f39e98dc978c5() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_7940653b8f524c34a987d6d8774af217 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_7940653b8f524c34a987d6d8774af217() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_84c943b62b964a5f84e586642e3af5fd : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_84c943b62b964a5f84e586642e3af5fd() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyGrabbable
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyGrabbable
        private sealed class TYPE_2e762b9aed5848c39384d8a1e92e9092 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_2e762b9aed5848c39384d8a1e92e9092() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable)) {
                this.AddMember("UseGravity", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("UseGravity", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_4e56f98b7d654782bdb1d62814d3fc31()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_415db0210f1540ab87ffc93a6bedca8f()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_18929598b69c49479b45c3bb09c2fa35()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_5c248e76f6254a9a898884c1370b85a2()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyGrabbable), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_5650a45307544aa5807255679929aae9()}));
            }
            
            private sealed class MTHD_4e56f98b7d654782bdb1d62814d3fc31 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_4e56f98b7d654782bdb1d62814d3fc31() {
                    this.Initialize("UseGravity", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("use", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyGrabbable)(obj)).UseGravity(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_415db0210f1540ab87ffc93a6bedca8f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_415db0210f1540ab87ffc93a6bedca8f() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_18929598b69c49479b45c3bb09c2fa35 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_18929598b69c49479b45c3bb09c2fa35() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_5c248e76f6254a9a898884c1370b85a2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_5c248e76f6254a9a898884c1370b85a2() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_5650a45307544aa5807255679929aae9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_5650a45307544aa5807255679929aae9() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxySlider
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxySlider
        private sealed class TYPE_dad19dd4e7a34ea98971163634af7e0c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_dad19dd4e7a34ea98971163634af7e0c() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxySlider)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e8e0f428aaa442689b2b4492ba342a2d()}));
                this.AddMember("SetSpeed", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetSpeed", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8f6db32584c244198867cfda88e2ce22()}));
                this.AddMember("GoTo", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GoTo", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_df80fe7cd7bb417092c69555fd58ba81()}));
                this.AddMember("SetStop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetStop", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_671789b4836840bfa4b08a4fcd01a671()}));
                this.AddMember("GetStop", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetStop", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cf3bf78e036a47f1a8ae1313e3446d6b()}));
                this.AddMember("StartMovement", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("StartMovement", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2d929e2bd8864dc0ad3e585e78a21b1b()}));
                this.AddMember("StopMovement", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("StopMovement", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_62948f2fb592468a9471f897d58cdb2d()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3f1bbc91179c455b9b23f15de5d1bf1d()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_255a4a360ed64e58b7f64e689fdb19b2()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_8445315c6dab42a7bff261ef0cda17a7()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxySlider), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2b4fb0aa8e0649809cc3210a405686ac()}));
            }
            
            private sealed class MTHD_e8e0f428aaa442689b2b4492ba342a2d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e8e0f428aaa442689b2b4492ba342a2d() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("slider", typeof(AimXRToolkit.Interactions.Slider), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxySlider(((AimXRToolkit.Interactions.Slider)(pars[0])));
                }
            }
            
            private sealed class MTHD_8f6db32584c244198867cfda88e2ce22 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8f6db32584c244198867cfda88e2ce22() {
                    this.Initialize("SetSpeed", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("speed", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).SetSpeed(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_df80fe7cd7bb417092c69555fd58ba81 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_df80fe7cd7bb417092c69555fd58ba81() {
                    this.Initialize("GoTo", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("distance", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).GoTo(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_671789b4836840bfa4b08a4fcd01a671 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_671789b4836840bfa4b08a4fcd01a671() {
                    this.Initialize("SetStop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("maxDisplacement", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).SetStop(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_cf3bf78e036a47f1a8ae1313e3446d6b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cf3bf78e036a47f1a8ae1313e3446d6b() {
                    this.Initialize("GetStop", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).GetStop();
                }
            }
            
            private sealed class MTHD_2d929e2bd8864dc0ad3e585e78a21b1b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2d929e2bd8864dc0ad3e585e78a21b1b() {
                    this.Initialize("StartMovement", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("reverse", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).StartMovement(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_62948f2fb592468a9471f897d58cdb2d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_62948f2fb592468a9471f897d58cdb2d() {
                    this.Initialize("StopMovement", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxySlider)(obj)).StopMovement();
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_3f1bbc91179c455b9b23f15de5d1bf1d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3f1bbc91179c455b9b23f15de5d1bf1d() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_255a4a360ed64e58b7f64e689fdb19b2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_255a4a360ed64e58b7f64e689fdb19b2() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_8445315c6dab42a7bff261ef0cda17a7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_8445315c6dab42a7bff261ef0cda17a7() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_2b4fb0aa8e0649809cc3210a405686ac : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_2b4fb0aa8e0649809cc3210a405686ac() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
        
        #region Descriptor of AimXRToolkit.Interactions.Proxies.ProxyHinge
        // Descriptor of AimXRToolkit.Interactions.Proxies.ProxyHinge
        private sealed class TYPE_09e41b71e36345b0834f968be26be7d7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor {
            
            internal TYPE_09e41b71e36345b0834f968be26be7d7() : 
                    base(typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge)) {
                this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9e467760365a4fbba71d758f621d8a91()}));
                this.AddMember("SetMinAngle", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetMinAngle", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a7e38df03cd444e682c84261d1db886a()}));
                this.AddMember("SetMaxAngle", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetMaxAngle", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cc284ce014ad4360a3514059ce3d2582()}));
                this.AddMember("UseLimits", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("UseLimits", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_7ac85eafe239462888716a9bf7dc8a44()}));
                this.AddMember("UseGravity", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("UseGravity", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_51a16ecfbce049ae8eb67ee6796a5041()}));
                this.AddMember("SetTarget", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetTarget", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3a451abe5f3143c0b86b90cea3e2fd24()}));
                this.AddMember("SetAngle", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetAngle", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e1d8372aeea645d696e10ca367ba1b6b()}));
                this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b2b65f06c6c747bbaf50f4104e1f85a9()}));
                this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_3eb3e4ec25774264ada3e33ace6f4a88()}));
                this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_dacc671e39e643a7a045ab1d183229bc()}));
                this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(AimXRToolkit.Interactions.Proxies.ProxyHinge), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e6eab98599cb4aefbc8999cba486826f()}));
            }
            
            private sealed class MTHD_9e467760365a4fbba71d758f621d8a91 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_9e467760365a4fbba71d758f621d8a91() {
                    this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("h", typeof(AimXRToolkit.Interactions.Hinge), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return new AimXRToolkit.Interactions.Proxies.ProxyHinge(((AimXRToolkit.Interactions.Hinge)(pars[0])));
                }
            }
            
            private sealed class MTHD_a7e38df03cd444e682c84261d1db886a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_a7e38df03cd444e682c84261d1db886a() {
                    this.Initialize("SetMinAngle", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("angle", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).SetMinAngle(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_cc284ce014ad4360a3514059ce3d2582 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_cc284ce014ad4360a3514059ce3d2582() {
                    this.Initialize("SetMaxAngle", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("angle", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).SetMaxAngle(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_7ac85eafe239462888716a9bf7dc8a44 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_7ac85eafe239462888716a9bf7dc8a44() {
                    this.Initialize("UseLimits", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("use", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).UseLimits(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_51a16ecfbce049ae8eb67ee6796a5041 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_51a16ecfbce049ae8eb67ee6796a5041() {
                    this.Initialize("UseGravity", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("use", typeof(bool), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).UseGravity(((bool)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_3a451abe5f3143c0b86b90cea3e2fd24 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3a451abe5f3143c0b86b90cea3e2fd24() {
                    this.Initialize("SetTarget", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("target", typeof(string), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).SetTarget(((string)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_e1d8372aeea645d696e10ca367ba1b6b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e1d8372aeea645d696e10ca367ba1b6b() {
                    this.Initialize("SetAngle", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("angle", typeof(float), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    ((AimXRToolkit.Interactions.Proxies.ProxyHinge)(obj)).SetAngle(((float)(pars[0])));
                    return MoonSharp.Interpreter.DynValue.Void;
                }
            }
            
            private sealed class MTHD_b2b65f06c6c747bbaf50f4104e1f85a9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_b2b65f06c6c747bbaf50f4104e1f85a9() {
                    this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetType();
                }
            }
            
            private sealed class MTHD_3eb3e4ec25774264ada3e33ace6f4a88 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_3eb3e4ec25774264ada3e33ace6f4a88() {
                    this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).ToString();
                }
            }
            
            private sealed class MTHD_dacc671e39e643a7a045ab1d183229bc : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_dacc671e39e643a7a045ab1d183229bc() {
                    this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).Equals(((object)(pars[0])));
                }
            }
            
            private sealed class MTHD_e6eab98599cb4aefbc8999cba486826f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor {
                
                internal MTHD_e6eab98599cb4aefbc8999cba486826f() {
                    this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
                }
                
                protected override object Invoke(MoonSharp.Interpreter.Script script, object obj, object[] pars, int argscount) {
                    return ((object)(obj)).GetHashCode();
                }
            }
        }
        #endregion
    }
}
